# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  SubscriptionId: '8911ade0-2192-425e-a08d-c27be185a83e'
  ResourceGroup: 'rg-test-insights'
  WorkspaceName: 'wks-insights-test01'

steps:
- powershell: |
   switch ("$(env)")
   {
       "prod" {"This is prod."; $Id="someIDrandomforprod"; $SP="Visual Studio Enterprise con MSDN (8911ade0-2192-425e-a08d-c27be185a83e)"}
       "test" {"This is test."; $Id="someIDrandomfortest"; $SP=ErickPuga-MSDN-Subs}
       "qa" {"This is qa."; $Id="someIDrandomforqa"}
       "sandbox" {"This is sandbox."; $Id="someIDrandomforsandbox"}
   }
   
   Write-Host $Id
   Write-Host $SP
  displayName: 'Set Variables'
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: '$SP'
    ScriptType: InlineScript
    Inline: |
     Install-Module -Name Az.OperationalInsights -Force
     
     $WorkspaceKey = Get-AzOperationalInsightsWorkspaceSharedKey -ResourceGroupName $(ResourceGroup) -Name $(WorkspaceName)
     $WorkspaceKeytoJson = $WorkspaceKey | ConvertTo-Json -Compress
     $WorkspaceKeyObject = $WorkspaceKeytoJson  |  ConvertFrom-Json
     $WorkspaceKeytoString  = $WorkspaceKeyObject.PrimarySharedKey    
     Write-Host "##vso[task.setvariable variable=primarykey]$WorkspaceKeytoString"

     $WorkspaceId = Get-AzOperationalInsightsWorkspace -ResourceGroupName $(ResourceGroup) -Name $(WorkspaceName)
     $WorkspaceIdtoJson = $WorkspaceId | ConvertTo-Json -Compress
     $WorkspaceIdObject = $WorkspaceIdtoJson  |  ConvertFrom-Json
     $WorkspaceIdtoString  = $WorkspaceIdObject.CustomerId
     Write-Host "##vso[task.setvariable variable=wksid]$WorkspaceIdtoString"

    
    azurePowerShellVersion: LatestVersion

- task: AzurePowerShell@3
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: 'ErickPuga-MSDN-Subs'
    ScriptType: InlineScript
    Inline: |
     Write-Host "This is the workspaceId" $env:WKSID
     Install-Script -Name Install-VMInsights -Force
     Install-VMInsights.ps1 -WorkspaceId $env:WKSID -WorkspaceKey $env:PRIMARYKEY -SubscriptionId $env:SubscriptionId -WorkspaceRegion eastus2 -ResourceGroup $env:ResourceGroup -Approve -ErrorAction SilentlyContinue
    preferredAzurePowerShellVersion: 3.8.0
