# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: ErickPuga-MSDN-Subs
    ScriptType: InlineScript
    Inline: | 

      
      Install-Module -Name Az.OperationalInsights -Force
      $WorkspaceKey = Get-AzOperationalInsightsWorkspaceSharedKey -ResourceGroupName '$(ResourceGroup)' -Name '$(WorkspaceName)'
    azurePowerShellVersion: LatestVersion

- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: ErickPuga-MSDN-Subs
    ScriptType: InlineScript
    Inline: | 
      Install-Script -Name Install-VMInsights -Force
      Install-VMInsights.ps1 -WorkspaceId '$(WorkspaceId)' -WorkspaceKey $(WorkspaceKey.PrimarySharedKey -SubscriptionId '$(SubscriptionId)' -WorkspaceRegion eastus2 -ResourceGroup '$(ResourceGroup)'
    azurePowerShellVersion: LatestVersion