# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  WorkspaceId: '88383834-63d1-4e04-a41f-7a0c1cbcd4b7'
  SubscriptionId: '8911ade0-2192-425e-a08d-c27be185a83e'
  ResourceGroup: 'rg-test-insights'
  WorkspaceName: 'wks-insights-test01'

steps:

- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: 'ErickPuga-MSDN-Subs'
    ScriptType: InlineScript
    Inline: |
     Install-Module -Name Az.OperationalInsights -Force
     
     $WorkspaceKey = Get-AzOperationalInsightsWorkspaceSharedKey -ResourceGroupName $(ResourceGroup) -Name $(WorkspaceName)
     $JsonObject = $WorkspaceKey | ConvertTo-Json -Compress
     $NewJsonObject = $JsonObject  |  ConvertFrom-Json
     $WorkspaceKeytoString  = $NewJsonObject.PrimarySharedKey
     
     Write-Host "##vso[task.setvariable variable=primarykey]$WorkspaceKeytoString"
    azurePowerShellVersion: LatestVersion

- task: AzurePowerShell@3
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: 'ErickPuga-MSDN-Subs'
    ScriptType: InlineScript
    Inline: |
     Install-Script -Name Install-VMInsights -Force
     Install-VMInsights.ps1 -WorkspaceId $env:WorkspaceId -WorkspaceKey $env:PRIMARYKEY -SubscriptionId $env:SubscriptionId -WorkspaceRegion eastus2 -ResourceGroup $env:ResourceGroup -Approve -ErrorAction SilentlyContinue
    preferredAzurePowerShellVersion: 3.8.0
