# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: ErickPuga-MSDN-Subs
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |      
      Install-Script -Name Install-VMInsights -Force
      Install-Module -Name Az.OperationalInsights -Force

- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: ErickPuga-MSDN-Subs
    ScriptType: InlineScript
    Inline: | 
      $SubscriptionId = "8911ade0-2192-425e-a08d-c27be185a83e"
      $WorkspaceId = "c37e78a5-2fd6-4a0e-8e7e-2b46b3946281"
      $ResourceGroup = "rg-test-insights"
      $WorkspaceName = "wks-insights-test01"
      $WorkspaceKey = Get-AzOperationalInsightsWorkspaceSharedKey -ResourceGroupName $ResourceGroup -Name $WorkspaceName
    azurePowerShellVersion: LatestVersion

